steps:
  - label: "Start Exercise"
    command: echo "Starting exercise steps..."
  - label: ":python: Run Sentence Function"
    key: "run_sentence"
    plugins:
      - docker#v5.12.0:
          image: "python:3.13"
    commands: 
      - "python -c 'import loremipsum; print(loremipsum.sentence(max_char=20))' >> result.txt"
      - echo "Generated sentence saved to result.txt"
      - "cat result.txt"
    artifact_paths: "result.txt" 
  - label: ":memo: Annotate Sentence Result"
    key: "annotate_sentence_result"
    depends_on: "run_sentence"
    commands: 
      - "buildkite-agent artifact download result.txt ."
      - "cat result.txt | buildkite-agent annotate --style 'success'"
  - label: ":python: Run Paragraph Function"
    key: "run_paragraph"
    depends_on: "annotate_sentence_result"
    if: build.jobs.annotate_sentence_result == "passed"
    plugins:
    - docker#v5.12.0:
        image: "python:3.13"
    commands: 
      - "python3 -c 'import loremipsum; print(loremipsum.paragraph(max_char=100))' >> result2.txt"
      - echo "Generated paragraph saved to result2.txt"
      - "cat result2.txt"
    artifact_paths: "result2.txt"
  - label: ":memo: Annotate Paragraph Result"
    key: "annotate_paragraph_result"
    depends_on: "run_paragraph"
    commands: 
      - "buildkite-agent artifact download result2.txt ."
      - "cat result2.txt | buildkite-agent annotate --style 'success'"
  - label: ":arrow_down: Download and Print Artifact"
    key: "download_print_artifact"
    depends_on: "annotate_paragraph_result"
    commands: 
      - "buildkite-agent artifact download result2.txt ."
      - "cat result2.txt"
  - label: "Push to Buildkite Docker Package Registries"
    key: "docker_package_registry"
    depends_on: "download_print_artifact"
    commands: 
      - TOKEN_VALUE=$$(buildkite-agent secret get DOCKER_TOKEN)
      - "docker login packages.buildkite.com/dl-trial/buildkite-container-registry -u buildkite -p $$TOKEN_VALUE"
      - "docker pull hello-world"
      - "docker tag hello-world packages.buildkite.com/dl-trial/buildkite-container-registry/custom-hello-world:latest"
      - "docker push packages.buildkite.com/dl-trial/buildkite-container-registry/custom-hello-world:latest"
  - label: "Pull Buildkite Docker Image and Run It"
    key: "test_docker_package_registry"
    depends_on: "docker_package_registry"
    commands:
      - TOKEN_VALUE=$$(buildkite-agent secret get DOCKER_TOKEN)
      - "docker login packages.buildkite.com/dl-trial/buildkite-container-registry -u buildkite -p $$TOKEN_VALUE"
      - "docker pull packages.buildkite.com/dl-trial/buildkite-container-registry/custom-hello-world@sha256:a3f53a068794afb31f76ae82f79c71db0fb05a3ec960c62cd15027e214d7dc7f"
      - "docker run packages.buildkite.com/dl-trial/buildkite-container-registry/custom-hello-world@sha256:a3f53a068794afb31f76ae82f79c71db0fb05a3ec960c62cd15027e214d7dc7f"
    