steps:
  - label: "Start Exercise"
    command: echo "Starting exercise steps..."
  - label: "Run Sentence Function"
    commands: 
      - "python -c 'import loremipsum; print(loremipsum.sentence(max_char=20))' >> result.txt"
    artifact_paths: "./result.txt" 
    plugins:
      - docker#v5.12.0:
          image: "python:3.13"
    key: "run-sentence"
  - label: "Annontate Result 1"
    commands: 
      - "buildkite-agent artifact download result.txt ./"
      - "cat ./result.txt | buildkite-agent annotate"
    key: "annotate-result1"
  - label: "Run Paragraph Function"
    depends_on: "annotate-result1"
    commands: |
      command: |
      if [ $$(buildkite-agent step get "outcome" --step "run-sentence") == "passed" && $$(buildkite-agent step get "outcome" --step "annotate-result1") == "passed" ]; then
         cat <<- YAML | buildkite-agent pipeline upload
         steps:
           - label: "Run Regression"
             command: "python3 -c 'import loremipsum; print(loremipsum.paragraph(max_char=100))' >> result2.txt"
             artifact_paths: "./result2.txt"
             plugins:
              - docker#v5.12.0:
                  image: "python:3.13"
      YAML
      fi
  - label: "Annontate Result 2"
    commands: 
      - "buildkite-agent artifact download result2.txt ./"
      - "cat ./result2.txt | buildkite-agent annotate"
  - label: "Download and Print Artifact"
    commands: 
      - "buildkite-agent artifact download result2.txt"
      - "cat result2.txt"
  - label: "Push to Buildkite Docker Package Registries"
    commands: 
      - "docker login packages.buildkite.com/dl-trial/buildkite-container-registry -u buildkite -p $DOCKER_TOKEN"
      - "docker pull hello-world"
      - "docker tag hello-world packages.buildkite.com/dl-trial/buildkite-container-registry/hello-world:1.0"
      - "docker push packages.buildkite.com/dl-trial/buildkite-container-registry/hello-world:1.0"
    