steps:
  - label: "Start"
    command: echo "Start build"
  - label: "Run Sentence Function and Annotate"
    command: 
      - "python3 -c 'import loremipsum; print(loremipsum.sentence(max_char=20))' >> ./artifacts/sentence_result.txt"
      - "cat ./artifacts/sentence_result.txt | buildkite-agent annotate"
    artifact_paths: "./artifacts" 
    plugins:
      - docker#v5.12.0:
          image: "python:3.13"
  - label: "Run Paragraph Function and Annotate"
    command: 
      - "python3 -c 'import loremipsum; print(loremipsum.paragraph(max_char=100))' >> ./artifacts/paragraph_result.txt"
      - "cat ./artifacts/paragraph_result.txt | buildkite-agent annotate"
    artifact_paths: "./artifacts" 
    plugins:
      - docker#v5.12.0:
          image: "python:3.13"
    