steps:
  - label: "Start Build"
    command: echo "Starting steps..."
  - label: "Run Sentence Function and Annotate"
    commands: 
      - "python -c 'import loremipsum; print(loremipsum.sentence(max_char=20))' >> result.txt"
    artifact_paths: "./result.txt" 
    plugins:
      - docker#v5.12.0:
          image: "python:3.13"
  - label: "Annontate"
    commands: 
      - "buildkite-agent artifact download result.txt ./"
      - "cat ./result.txt | buildkite-agent annotate"
  # - label: "Run Paragraph Function and Annotate"
  #   commands: 
  #     - "python3 -c 'import loremipsum; print(loremipsum.paragraph(max_char=100))' >> ./artifacts/paragraph_result.txt"
  #     - "cat ./artifacts/paragraph_result.txt | buildkite-agent annotate"
  #   artifact_paths: "./artifacts" 
  #   plugins:
  #     - docker#v5.12.0:
  #         image: "python:3.13"
    